# Generated by Django 3.2 on 2021-04-21 22:51

# Generated by Django 3.2 on 2021-04-21 22:11

from django.db import migrations

def create_data(apps, schema_editor):
    Songs = apps.get_model('musicapp', 'Songs')
    Songs(song="Paparazzi", artist="Lady Gaga", album="The Fame", genre="Pop", year="2007").save()

class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
