# Generated by Django 3.2 on 2021-04-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.CharField(default='kek', max_length=200),
            preserve_default=False,
        ),
    ]
